### ISSUE TITLE
Markdown rendering and highlight.min.js issues

### ISSUE THREAD

**Issue by mmulli** [MBvisti/awesome-blog#3]
I noticed that highlight.min.js is missing from your tutorial in regards to how to set it up. I could make some guesses but would appreciate a tip in case it needs to play nicely with the existing tailwind css setup.

Btw, thanks for putting in the effort for such an easy follow tutorial. Perfect starter for someone like myself wanting to expand my rust skills toward the web. I'm also keen to starting sharing back via blogging thanks to this.

A quick follow up observation is that the markdown for the blog posts themselves was not distinguishing itself for different heading types that are rendered out to HMTL such as h1, h2, etc. Though I'm guessing that's a different css issue?

**Comment by RoskiDeluge** [comment]
I'm getting the same issue with the markdown not distinguishing between heading types and also not rendering paragraph spacing.

**Comment by mmulli** [comment]
Hi @RoskiDeluge I found out that there is a special Typography plugin for tailwind css that serves the purpose of rendering dynamic HTML content such as content generated from markdown. For my own [site](https://codetrance.io/) I didn't end up opting for that level of complexity and went for something simpler by just adding an additional css file to style the blog posts. For example:

I added this line to my base.html file:
` <link rel="stylesheet" type="text/css" href="/static/css/post.css">`

My post.html ended up looking like this:
```
{% extends "base.html" %}

{% block title %}{{ meta_data.title }} | by (My Name) {% endblock title %}

{% block header %}
<div class="relative mt-2 ml-4 flex w-full h-full justify-end">
    <a class="absolute left-0 font-semibold hover:underline mr-10" href="/">Go back</a>
    <a class="font-semibold hover:underline mr-10" href="/">Blog</a>
    <a class="font-semibold hover:underline mr-10" href="/">Projects</a>
</div>
{% endblock header %}

{% block content %}
<div class="w-full h-full px-4 md:px-6 text-base text-gray-800 leading-normal">
    <article id="article-content">
        {{ post | safe }}
    </article>
</div>
{% endblock content %}

{% block footer %}
    <div class="flex w-full h-full justify-center items-center">
        &copy; 2023 by <a class="pl-2" href="">My Name</a>
    </div>
{% endblock footer %}
```

It's a while ago since I did this but I think that "article-content" in the above may have had significance.

And my post.css file is as follows:

```css
/* 
The descendant combinator 'article element' is used to apply the css only to 
descendants of the article element. This allows tailwindcss 
to still function fine outside of article. 

Note: Tailwindcss is still impacting some elements within this blog that are not explicitly called out here
and that have been specified in the article elements html as tailwind class names. For example, normal text
is still controlled by the tailwind classes on the article element html.
*/

/* article {
  font-family:
    ui-sans-serif,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    Segoe UI,
    Roboto,
    Helvetica Neue,
    Arial,
    Noto Sans,
    sans-serif,
    Apple Color Emoji,
    Segoe UI Emoji,
    Segoe UI Symbol,
    Noto Color Emoji !important;
} */

article h1 {
  display: block;
  font-size: 2em;
  margin-top: 0.67em;
  margin-bottom: 0.67em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article h2 {
  display: block;
  font-size: 1.5em;
  margin-top: 0.83em;
  margin-bottom: 0.83em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article h3 {
  display: block;
  font-size: 1.17em;
  margin-top: 1em;
  margin-bottom: 1em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article h4 {
  display: block;
  margin-top: 1.33em;
  margin-bottom: 1.33em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article h5 {
  display: block;
  font-size: .83em;
  margin-top: 1.67em;
  margin-bottom: 1.67em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article h6 {
  display: block;
  font-size: .67em;
  margin-top: 2.33em;
  margin-bottom: 2.33em;
  margin-left: 0;
  margin-right: 0;
  font-weight: bold;
}

article code {
  font-size: 0.65em;
}

article code,
img {
  margin-top: 1em;
  margin-bottom: 1em;
}

article p {
  font-size: 1;
  line-height: 1.6em;
  margin-bottom: 1em;
}

article ul {
  font-size: 1;
  line-height: 1.6em;
  margin-left: 1em;
}

article li {
  font-size: 1;
  line-height: 1.6em;
}

```

(edit) Oh and I also needed to setup a tailwind.config.js file with  a disabledCss object. See below:

```js
// Manually disabled code block CSS for tailwind 
// because we wish to style this using some custom css
// that works on markdown output without the tailwind 
// typography plugin. Reference for disabling:
// https://building.hellonext.co/blog/disable-tailwind-prose-code
const disabledCss = {
	'code::before': false,
	'code::after': false,
	'blockquote p:first-of-type::before': false,
	'blockquote p:last-of-type::after': false,
	pre: false,
	code: false,
	'pre code': false,
	'code::before': false,
	'code::after': false,
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["../templates/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

This is all a workaround but it worked well enough for me. If you want to do it properly do check out the Typography plugin for tailwind css. And there might be other strategies too.

 I hope this helps!
